openapi: 3.0.3
info:
  title: CivicSage
  description: |
    CivicSage is a service that allows you to index files and websites.
  version: 0.7.0

servers:
  - url: localhost:8080/api/v1
    description: Local development server

paths:
  /index/file:
    $ref: './paths/index.yaml#/file'
  /index/url:
    $ref: './paths/index.yaml#/url'
  /search:
    $ref: './paths/search.yaml'
  /files:
    $ref: './paths/files.yaml'
  /feedback:
    $ref: './paths/feedback.yaml'
  /system/info:
    $ref: './paths/system.yaml#/info'
  /system/metadata-keys:
    $ref: './paths/system.yaml#/metadata-keys'
  /completions/chat:
    $ref: './paths/completions.yaml#/chat'
  /sources:
    $ref: './paths/sources.yaml'
  /sources/websites/update:
    $ref: './paths/sources-websites-update.yaml'

components:
  schemas:
    searchQuery:
      $ref: './components/schemas/searchQuery.yaml'
    searchResult:
      $ref: './components/schemas/searchResult.yaml'
    feedback:
      $ref: './components/schemas/feedback.yaml'
    systemInfo:
      $ref: './components/schemas/systemInfo.yaml'
    fileSource:
      $ref: './components/schemas/fileSource.yaml'
    websiteSource:
      $ref: './components/schemas/websiteSource.yaml'
    chat:
      $ref: './components/schemas/chat.yaml'
    chatMessage:
      $ref: './components/schemas/chatMessage.yaml'
    chatFile:
      $ref: './components/schemas/chatFile.yaml'
